#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# This code is generated by AI
""" main.py -- Chessboard hardware loop
Runs on the Raspberry Pi inside the physical chessboard.

UX contract implemented here (matched to the Flask API in api.py):

  * Local moves are confirmed with a WHITE flash on the from/to squares.
  * Opponent moves (Stockfish engine, Lichess opponent, or a move that
    arrived on the shared HVH board from another board/client) blink
    RED on the source square and GREEN on the destination square
    (orange if it gives check) and wait for the player to execute them.

Modes:
  stockfish  Human vs engine (white | black | alternate via play_as).
  hvh        Human vs human on this board (or two boards sharing the
             server's /hvh-* game).
  lichess    Human vs online opponent.
  auto       Detect the active game automatically:
               1. /hvh-status   state == "playing"  -> hvh
               2. /lichess-status state active      -> lichess
               3. otherwise                         -> stockfish

             Start an HVH game from another client (web UI / curl) with
             POST /hvh-start; end it with POST /reset-hvh-game.

HVH notes and server quirks this client works around:
  * /hvh-status returns JSON {"fen": ..., "state": "idle"|"playing"}; the
    client parses that (legacy bare-FEN responses are tolerated too).
  * If the server never refreshes status["fen"] on make-move, the remote
    FEN is a frozen snapshot. This loop therefore never rolls back from a
    server FEN that hasn't *changed* between polls.
  * A changed server FEN that sits *behind* the local board (1..4 plies)
    is a server-side /hvh-undo: the local logical board is rewound to
    match, so the physical board and LEDs agree again.
  * A server FEN that is *ahead* by legal forward moves is an inbound
    move from another board/client and is prompted red -> green.
  * On entering hvh mode the client POSTs /hvh-start so the shared
    session is visible to other clients and to auto-detection.
  * In auto mode the loop leaves hvh automatically when the server's
    hvh session goes idle (someone POSTed /reset-hvh-game).

Other server caveats (unpatched):
  - The lichess results dict drops the player's colour when the game
    state changes to "playing"; the client infers colour from the
    physical board (see _apply_lichess_moves). A one-line server patch
    (include "color": self.color in update()) makes it instant.
  - Each POST /update-lichess-game spawns a new stream thread; the
    client calls it sparingly and restarts it only if it looks dead.
  - HVH's HumanGame.make_move() does not validate legality server-side;
    this client only sends legal moves (and validates locally).
"""

from __future__ import annotations

import json
import logging
import re
import signal
import sys
import threading
import time
import traceback
from collections import deque
from dataclasses import dataclass, field
from typing import Deque, Dict, List, Optional, Set, Tuple

import chess
import requests

# --------------------------------------------------------------------------
# Configuration
# --------------------------------------------------------------------------
@dataclass
class Config:
    base_url: str = "http://127.0.0.1:5000"
    mode: str = "auto"          # "auto" | "stockfish" | "hvh" | "lichess"
    led_brightness: int = 150
    poll_interval: float = 0.03
    debounce_reads: int = 3
    simulate: bool = False
    reset_on_start: bool = True
    auto_restart: bool = True
    resync_interval: float = 8.0
    lichess_poll_interval: float = 0.6
    hvh_poll_interval: float = 0.6    # inbound poll of /hvh-status
    mode_check_interval: float = 2.0
    request_timeout: float = 5.0
    engine_timeout: float = 30.0
    retry_backoff: float = 0.6
    highlight_delay: float = 0.7
    guidance_delay: float = 4.0
    prompt_blink_hz: float = 1.5
    play_as: str = "white"      # stockfish mode: "white" | "black" | "alternate"
    auto_seek: bool = False     # lichess: POST /search-and-join... when idle
    lichess_stale_after: float = 120.0  # restart updater stream if no changes
    log_level: str = "INFO"


DEFAULT_CONFIG = Config(
    base_url="http://127.0.0.1:5000",
    mode="auto",
    request_timeout=5.0,
    led_brightness=150,
    simulate=False,
    poll_interval=0.03,
    debounce_reads=3,
    reset_on_start=True,
    auto_restart=True,
    engine_timeout=30.0,
    resync_interval=8.0,
    lichess_poll_interval=0.6,
    hvh_poll_interval=0.6,
    mode_check_interval=2.0,
    retry_backoff=0.6,
    highlight_delay=0.7,
    guidance_delay=4.0,
    prompt_blink_hz=1.5,
    play_as="white",
    auto_seek=False,
    lichess_stale_after=120.0,
    log_level="INFO",
)

# --------------------------------------------------------------------------
# Hardware import fallback
# --------------------------------------------------------------------------
try:
    from hardware import leds as hw_leds  # type: ignore
    from hardware import matrix as hw_matrix  # type: ignore

    _HARDWARE_IMPORT_ERROR: Optional[Exception] = None
except Exception as exc:
    hw_leds = None
    hw_matrix = None
    _HARDWARE_IMPORT_ERROR = exc

LETTERS = "abcdefgh"
UCI_RE = re.compile(r"^[a-h][1-8][a-h][1-8][qrbn]?")

# LED colours
BLACK = (0, 0, 0)
BROWN = (139, 69, 19)
WHITE = (255, 255, 255)
RED = (255, 0, 0)
DIM_RED = (60, 0, 0)
GREEN = (0, 255, 0)
DIM_GREEN = (0, 60, 0)
YELLOW = (255, 200, 0)
BLUE = (0, 80, 255)
ORANGE = (255, 120, 0)
GOLD = (200, 200, 0)

INITIAL_OCCUPANCY: Set[str] = {
    chess.square_name(sq) for sq in chess.SquareSet(chess.Board().occupied)
}

_ALTERNATE_COLOR_FLIP: List[bool] = [False]
START_FEN = chess.Board().fen()

# --------------------------------------------------------------------------
# Matrix <-> chess-square coordinate mapping
# --------------------------------------------------------------------------
def square_name(y_index: int, x_index: int) -> str:
    """Map raw matrix state[y][x] to a chess square name.

    The physical board is wired with the raw sensor rows reversed relative
    to the playing side (rank 1 at raw y=7, rank 8 at raw y=0). Flip only
    the y axis so the displayed board and physical board match.
    """
    y_index = 7 - y_index
    return f"{LETTERS[x_index]}{y_index + 1}"


def matrix_coords(square: str) -> Tuple[int, int]:
    """Inverse of square_name(): chess square name -> raw matrix (y, x)."""
    file_idx = LETTERS.index(square[0])
    rank_idx = int(square[1]) - 1
    return 7 - rank_idx, file_idx


def occupancy_of(board: chess.Board) -> Set[str]:
    return {chess.square_name(sq) for sq in chess.SquareSet(board.occupied)}


def setup_logging(cfg: Config) -> logging.Logger:
    logging.basicConfig(
        level=getattr(logging, cfg.log_level, logging.INFO),
        format="%(asctime)s %(levelname)-7s %(message)s",
        datefmt="%H:%M:%S",
    )
    return logging.getLogger("chessboard")

# --------------------------------------------------------------------------
# Hardware fallbacks
# --------------------------------------------------------------------------
class MockMatrix:
    def __init__(self):
        self._state = [[0] * 8 for _ in range(8)]

    def get_state(self):
        return [row[:] for row in self._state]

    def set_state(self, state):
        self._state = [row[:] for row in state]


class MockLEDStrip:
    def __init__(self, brightness=150):
        self.brightness = brightness
        self.pixels: Dict[str, Tuple[int, int, int]] = {}

    def set_square_rgb(self, square, rgb):
        self.pixels[square] = tuple(rgb)

    def set_all_rgb(self, rgb):
        for sq in list(self.pixels.keys()):
            self.pixels[sq] = tuple(rgb)

    def set_matrix_rgb(self, rgb_white, rgb_black):
        self.pixels["__base_white__"] = tuple(rgb_white)
        self.pixels["__base_black__"] = tuple(rgb_black)

    def update(self):
        pass


def create_matrix(cfg: Config, log: logging.Logger):
    if cfg.simulate:
        log.warning("SIMULATE=True: using mock matrix")
        return MockMatrix()
    if hw_matrix is None:
        log.warning(
            "hardware.matrix unavailable (%s); using mock",
            _HARDWARE_IMPORT_ERROR,
        )
        return MockMatrix()
    try:
        return hw_matrix.ChessboardMatrix()
    except Exception as exc:
        log.warning("failed to open serial matrix (%s); using mock", exc)
        return MockMatrix()


def create_leds(cfg: Config, log: logging.Logger):
    if cfg.simulate:
        log.warning("SIMULATE=True: using mock LED strip")
        return MockLEDStrip(cfg.led_brightness)
    if hw_leds is None:
        log.warning(
            "hardware.leds unavailable (%s); using mock",
            _HARDWARE_IMPORT_ERROR,
        )
        return MockLEDStrip(cfg.led_brightness)
    try:
        return hw_leds.LEDStrip(cfg.led_brightness)
    except Exception as exc:
        log.warning("failed to init LED strip (%s); using mock", exc)
        return MockLEDStrip(cfg.led_brightness)

# --------------------------------------------------------------------------
# LED rendering
# --------------------------------------------------------------------------
class LedView:
    def __init__(self, strip, log: logging.Logger):
        self.strip = strip
        self.log = log
        self._warned = False
        self._last_key = None

    def _safe(self, fn, *args, **kwargs):
        try:
            fn(*args, **kwargs)
        except Exception as exc:
            if not self._warned:
                self.log.warning("LED write failed (%s); continuing without LEDs", exc)
                self._warned = True

    def render(self, overlays: Dict[str, Tuple[int, int, int]]):
        key = tuple(sorted(overlays.items()))
        if key == self._last_key:
            return
        self._last_key = key
        self._safe(self.strip.set_matrix_rgb, BROWN, BLACK)
        for sq, rgb in overlays.items():
            self._safe(self.strip.set_square_rgb, sq, rgb)
        self._safe(self.strip.update)

    def flash_all(self, rgb, times=2, delay=0.15):
        for _ in range(times):
            self._safe(self.strip.set_all_rgb, rgb)
            self._safe(self.strip.update)
            time.sleep(delay)
            self._safe(self.strip.set_matrix_rgb, BROWN, BLACK)
            self._safe(self.strip.update)
            time.sleep(delay)
        self._last_key = None

    def clear(self):
        self._last_key = None
        self.render({})

# --------------------------------------------------------------------------
# Move detection
# --------------------------------------------------------------------------
class DebouncedReader:
    def __init__(self, matrix, debounce_reads: int, log: logging.Logger):
        self.matrix = matrix
        self.debounce_reads = max(1, debounce_reads)
        self.log = log
        self.confirmed = [[0] * 8 for _ in range(8)]
        self._candidate = [[0] * 8 for _ in range(8)]
        self._streak = [[0] * 8 for _ in range(8)]
        self._primed = False

    def _read_raw(self) -> Optional[List[List[int]]]:
        try:
            return self.matrix.get_state()
        except Exception as exc:
            self.log.debug("matrix read failed: %s", exc)
            return None

    def poll(self) -> Set[str]:
        raw = self._read_raw()
        if raw is None:
            return set()

        changed: Set[str] = set()
        for y in range(8):
            for x in range(8):
                val = 1 if raw[y][x] else 0
                if val == self._candidate[y][x]:
                    self._streak[y][x] += 1
                else:
                    self._candidate[y][x] = val
                    self._streak[y][x] = 1

                if self._streak[y][x] >= self.debounce_reads and self.confirmed[y][x] != val:
                    self.confirmed[y][x] = val
                    if self._primed:
                        changed.add(square_name(y, x))
        self._primed = True
        return changed

    def is_occupied(self, sq: str) -> bool:
        y, x = matrix_coords(sq)
        return bool(self.confirmed[y][x])

    def occupied_squares(self) -> Set[str]:
        out = set()
        for y in range(8):
            for x in range(8):
                if self.confirmed[y][x]:
                    out.add(square_name(y, x))
        return out


class MoveFinder:
    LIFT_TTL = 20.0

    def __init__(self):
        self.lifted: Dict[str, float] = {}

    def reset(self):
        self.lifted.clear()

    def on_lift(self, square: str, now: float):
        self.lifted[square] = now

    def on_place(self, square: str, now: float, board: chess.Board) -> Optional[str]:
        self._expire(now)
        self.lifted.pop(square, None)

        candidates = []
        for from_sq in list(self.lifted.keys()):
            uci = self._try_move(board, from_sq, square)
            if uci:
                candidates.append((from_sq, uci))

        if not candidates:
            return None

        if len(candidates) == 1:
            from_sq, uci = candidates[0]
        else:
            candidates.sort(key=lambda c: -self.lifted.get(c[0], 0))
            from_sq, uci = candidates[0]

        self.lifted.pop(from_sq, None)
        return uci

    def _expire(self, now: float):
        expired = [sq for sq, t in self.lifted.items() if now - t > self.LIFT_TTL]
        for sq in expired:
            self.lifted.pop(sq, None)

    @staticmethod
    def _try_move(board: chess.Board, from_sq: str, to_sq: str) -> Optional[str]:
        for suffix in ("", "q", "r", "b", "n"):
            try:
                move = chess.Move.from_uci(from_sq + to_sq + suffix)
            except ValueError:
                continue
            if move in board.legal_moves:
                return move.uci()

        # Castling: king lifted, dropped on the rook's home square.
        try:
            piece = board.piece_at(chess.parse_square(from_sq))
        except ValueError:
            piece = None
        if piece is not None and piece.piece_type == chess.KING:
            for move in board.legal_moves:
                if (
                    board.is_castling(move)
                    and chess.square_name(move.from_square) == from_sq
                    and MoveFinder._castle_rook_square(board, move) == to_sq
                ):
                    return move.uci()
        return None

    @staticmethod
    def _castle_rook_square(board: chess.Board, move: chess.Move) -> Optional[str]:
        king_from = chess.square_name(move.from_square)
        if board.is_kingside_castling(move):
            return "h1" if king_from == "e1" else "h8"
        if board.is_queenside_castling(move):
            return "a1" if king_from == "e1" else "a8"
        return None

# --------------------------------------------------------------------------
# Mirror tasks (opponent-move execution queue)
# --------------------------------------------------------------------------
@dataclass
class MirrorTask:
    """An opponent move awaiting physical execution by the local player."""
    uci: str
    to_square: str
    from_squares: Set[str] = field(default_factory=set)  # blink RED here
    match_keys: Set[str] = field(default_factory=set)     # "" gestures
    check_sq: Optional[str] = None                       # orange check highlight
    deferred_gameover: Optional[Tuple[Optional[bool], str]] = None


def _castle_rook_transfer(pre_board: chess.Board, move: chess.Move) -> Tuple[str, str]:
    """rook_from -> rook_to for a standard-chess castling move."""
    king_from = chess.square_name(move.from_square)
    rank = king_from[1]
    if pre_board.is_kingside_castling(move):
        return f"h{rank}", f"f{rank}"
    return f"a{rank}", f"d{rank}"

# --------------------------------------------------------------------------
# API client
# --------------------------------------------------------------------------
class GameClient:
    def __init__(self, cfg: Config, log: logging.Logger):
        self.cfg = cfg
        self.log = log
        self._tls = threading.local()

    @property
    def session(self) -> requests.Session:
        sess = getattr(self._tls, "session", None)
        if sess is None:
            sess = requests.Session()
            self._tls.session = sess
        return sess

    def _request(self, method: str, path: str, retries: int, **kwargs) -> Optional[requests.Response]:
        url = f"{self.cfg.base_url}{path}"
        kwargs.setdefault("timeout", self.cfg.request_timeout)
        last_exc = None
        for attempt in range(1, retries + 1):
            try:
                return self.session.request(method, url, **kwargs)
            except requests.RequestException as exc:
                last_exc = exc
                self.log.debug("%s %s failed (attempt %d/%d): %s",
                               method, path, attempt, retries, exc)
                if attempt < retries:
                    time.sleep(self.cfg.retry_backoff * attempt)
        self.log.warning("%s %s unreachable after %d attempts: %s",
                         method, path, retries, last_exc)
        return None

    def get_text(self, path: str, retries: int = 2) -> Optional[str]:
        resp = self._request("GET", path, retries)
        if resp is None or resp.status_code >= 400:
            return None
        return resp.text.strip()

    def get_json(self, path: str, retries: int = 2) -> Optional[dict]:
        resp = self._request("GET", path, retries)
        if resp is None or resp.status_code >= 400:
            return None
        try:
            return resp.json()
        except ValueError:
            return None

    def post(self, path: str, json_body: Optional[dict] = None, retries: int = 1,
             timeout: Optional[float] = None) -> Optional[str]:
        kwargs = {}
        if timeout is not None:
            kwargs["timeout"] = timeout
        resp = self._request("POST", path, retries, json=json_body, **kwargs)
        if resp is None:
            return None
        return resp.text.strip()

    # -- stockfish ---------------------------------------------------

    def reset_stockfish(self) -> bool:
        return self.post("/reset-stockfish-game", retries=3) == "200"

    def stockfish_fen(self) -> Optional[str]:
        return self.get_text("/stockfish-status")

    def sf_make_human_move(self, uci: str) -> bool:
        return self.post("/sf-make-human-move", json_body={"move": uci}, retries=2) == "200"

    def sf_play(self) -> Optional[str]:
        body = self.post("/sf-play", retries=1, timeout=self.cfg.engine_timeout)
        if body and UCI_RE.match(body):
            return body
        if body:
            self.log.info("engine could not move (%s) -- likely game over", body)
        return None

    # -- hvh -----------------------------------------------------------

    def reset_hvh(self) -> bool:
        return self.post("/reset-hvh-game", retries=3) == "200"

    def hvh_status(self) -> Optional[dict]:
        """GET /hvh-status -> {"fen": ..., "state": "idle"|"playing"}.

        Tolerates legacy servers that answer with a bare FEN string.
        """
        text = self.get_text("/hvh-status", retries=1)
        if not text:
            return None
        try:
            data = json.loads(text)
        except ValueError:
            # legacy: a bare FEN
            return {"fen": text, "state": "playing"}
        if isinstance(data, dict):
            return {"fen": data.get("fen"), "state": data.get("state", "playing")}
        return None

    def hvh_start(self) -> bool:
        """POST /hvh-start: mark the shared HVH game as 'playing'."""
        return self.post("/hvh-start", retries=2) is not None

    def hvh_make_move(self, uci: str) -> bool:
        return self.post("/hvh-make-move", json_body={"move": uci}, retries=2) == "200"

    # -- lichess --------------------------------------------------------

    def lichess_status(self) -> Optional[dict]:
        return self.get_json("/lichess-status", retries=1)

    def li_make_move(self, uci: str) -> bool:
        return self.post("/li-make-move", json_body={"move": uci}, retries=2) == "success"

    def li_search(self) -> bool:
        return self.post("/search-and-join-lichess-game", retries=1) == "success"

    def li_update_stream(self) -> bool:
        return self.post("/update-lichess-game", retries=1) == "success"

# --------------------------------------------------------------------------
# Game loop
# --------------------------------------------------------------------------
class GameLoop:
    def __init__(self, cfg: Config, matrix, leds: LedView, client: GameClient, log: logging.Logger):
        self.cfg = cfg
        self.matrix = matrix
        self.leds = leds
        self.client = client
        self.log = log

        self.reader = DebouncedReader(matrix, cfg.debounce_reads, log)
        self.finder = MoveFinder()
        self.board = chess.Board()

        self.mode: Optional[str] = None
        # awaiting_human | awaiting_engine | pending_execution | game_over
        self.state = "awaiting_human"

        # FIFO of opponent moves awaiting physical execution (red->green).
        self.mirror_tasks: Deque[MirrorTask] = deque()

        self._engine_event = threading.Event()
        self._engine_result: Optional[str] = None
        self._engine_started = 0.0
        self._engine_inflight = False
        self._engine_generation = 0           # invalidates stale engine threads

        self._confirm_move: Optional[str] = None
        self._confirm_squares: List[str] = []
        self._confirm_until = 0.0

        self._mismatch_since: Optional[float] = None
        self._missing: Set[str] = set()
        self._extra: Set[str] = set()

        self._reset_candidate_since: Optional[float] = None
        self._hvh_pending_adoption: Optional[chess.Board] = None
        self._hvh_fen_history: Set[str] = set()
        self._hvh_last_state: Optional[str] = None
        self._hvh_last_server_fen: Optional[str] = None
        self._hvh_cache: Optional[dict] = None
        self._hvh_cache_time = 0.0

        self.human_color: Optional[bool] = chess.WHITE
        self.lichess_ply_count = 0
        self._li_moves: List[str] = []
        self._li_initial_fen: Optional[str] = None
        self._li_waiting = False
        self._li_stream_started = False
        self._li_stream_post_time = 0.0
        self._li_last_change = time.time()
        self._li_seek_requested = False

        self.last_resync = 0.0
        self.last_lichess_poll = 0.0
        self.last_hvh_poll = 0.0
        self.last_mode_check = 0.0
        self.running = True

        signal.signal(signal.SIGINT, self._on_signal)
        signal.signal(signal.SIGTERM, self._on_signal)

    def _on_signal(self, signum, frame):
        self.log.info("received signal %s, shutting down...", signum)
        self.running = False

    # ------------------------------------------------------------------
    # Mode management
    # ------------------------------------------------------------------

    def _detect_mode(self) -> str:
        forced = self.cfg.mode
        if forced in ("stockfish", "hvh", "lichess"):
            return forced
        # HVH takes priority: it is always a deliberate local action, and
        # the lichess status can stay stuck at "playing" after a game ends.
        hvh = self._hvh_snapshot()
        if hvh and hvh.get("state") == "playing":
            return "hvh"
        status = self.client.lichess_status()
        if status and status.get("state") in ("searching", "found", "playing"):
            return "lichess"
        return "stockfish"

    def _resolve_stockfish_color(self) -> bool:
        """Resolve the colour the local human plays vs Stockfish."""
        pref = (self.cfg.play_as or "white").lower()
        if pref == "black":
            _ALTERNATE_COLOR_FLIP[0] = False
            return chess.BLACK
        if pref == "alternate":
            _ALTERNATE_COLOR_FLIP[0] = not _ALTERNATE_COLOR_FLIP[0]
            return chess.BLACK if _ALTERNATE_COLOR_FLIP[0] else chess.WHITE
        _ALTERNATE_COLOR_FLIP[0] = False
        return chess.WHITE

    def _enter_mode(self, mode: str, adopt_server: bool = False):
        self.log.info("entering mode: %s", mode)
        self.mode = mode
        self._engine_generation += 1          # invalidate stale /sf-play workers
        self.finder.reset()
        self.state = "awaiting_human"
        self.mirror_tasks.clear()
        self._confirm_move = None
        self._confirm_squares = []
        self._confirm_until = 0.0
        self._mismatch_since = None
        self._missing = set()
        self._extra = set()
        self._reset_candidate_since = None
        self._hvh_pending_adoption = None
        self._engine_event.clear()
        self._engine_inflight = False

        if mode == "stockfish":
            if self.cfg.reset_on_start:
                self.client.reset_stockfish()
            self.board = chess.Board()
            self.human_color = self._resolve_stockfish_color()
            self.log.info("stockfish: you play %s",
                          "white" if self.human_color == chess.WHITE else "black")
        elif mode == "hvh":
            if adopt_server:
                # Take over an externally started session without wiping it.
                snap = self._hvh_snapshot(force=True)
                fen = (snap or {}).get("fen")
                try:
                    self.board = chess.Board(fen) if fen else chess.Board()
                except ValueError:
                    self.board = chess.Board()
                self.log.info("hvh: joined server session at %s",
                              self.board.fen().split()[0])
                self._hvh_last_server_fen = self.board.fen()
            elif self.cfg.reset_on_start:
                # Fresh game, and tell the server it is playing.
                self.client.reset_hvh()
                self.board = chess.Board()
                self.client.hvh_start()
                self.log.info("hvh: started a fresh server game")
                self._hvh_last_server_fen = START_FEN
            else:
                # Resume whatever the server board currently holds.
                fen = (self._hvh_snapshot(force=True) or {}).get("fen")
                try:
                    self.board = chess.Board(fen) if fen else chess.Board()
                except ValueError:
                    self.board = chess.Board()
                self.client.hvh_start()
                self._hvh_last_server_fen = self.board.fen()
            self.human_color = None
            self.last_hvh_poll = 0.0
            self._hvh_fen_history = {self.board.fen()}
            self._hvh_last_state = "playing"
        elif mode == "lichess":
            self.board = chess.Board()
            self.lichess_ply_count = 0
            self._li_moves = []
            self._li_initial_fen = None
            self._li_waiting = False
            self._li_stream_started = False
            self._li_stream_post_time = 0.0
            self._li_last_change = time.time()
            self._li_seek_requested = False
            self.human_color = None
            self.last_lichess_poll = 0.0       # poll immediately on next tick

        self.leds.clear()
        self._kick_engine_if_needed()

    # ------------------------------------------------------------------
    # HVH helpers
    # ------------------------------------------------------------------

    def _hvh_snapshot(self, force: bool = False) -> Optional[dict]:
        now = time.time()
        if not force and self._hvh_cache and now - self._hvh_cache_time < 1.0:
            return self._hvh_cache
        snap = self.client.hvh_status()
        if snap is not None:
            self._hvh_cache = snap
            self._hvh_cache_time = now
        return snap

    def _note_fen(self):
        if self.mode == "hvh":
            self._hvh_fen_history.add(self.board.fen())

    def _plies_behind(self, target: chess.Board) -> Optional[int]:
        """How many plies target sits behind the local board.

        Returns None if target is not an ancestor of the current local
        position (i.e. not reachable by undoing moves).
        """
        probe = self.board.copy()  # includes the move stack
        for k in range(len(probe.move_stack) + 1):
            if probe.fen() == target.fen():
                return k
            if not probe.move_stack:
                break
            probe.pop()
        return None

    def _rewind_hvh(self, target: chess.Board):
        """Rewind the local logical board after a server-side undo."""
        if self.board.move_stack:
            while self.board.fen() != target.fen() and self.board.move_stack:
                self.board.pop()
        if self.board.fen() != target.fen():
            self.board = target.copy(stack=False)
        self.finder.reset()
        self._mismatch_since = None
        self.log.info("hvh: server undo detected; rewound local board to %s",
                      target.fen().split()[0])
        self._note_fen()
        self._check_game_over()

    # ------------------------------------------------------------------
    # Main loop
    # ------------------------------------------------------------------

    def run(self):
        self.log.info("starting chessboard loop (base_url=%s)", self.cfg.base_url)
        mode = self._detect_mode()
        self._enter_mode(mode, adopt_server=(mode == "hvh" and self.cfg.mode == "auto"))
        self.last_resync = time.time()

        while self.running:
            try:
                self._tick()
            except Exception:
                self.log.error("unexpected error in main loop:\n%s",
                               traceback.format_exc())
                time.sleep(1.0)
            time.sleep(self.cfg.poll_interval)

        self.leds.clear()
        self.log.info("shutdown complete")

    def _tick(self):
        now = time.time()
        changed = self.reader.poll()

        lifts = sorted(sq for sq in changed if not self.reader.is_occupied(sq))
        places = sorted(sq for sq in changed if self.reader.is_occupied(sq))

        for sq in lifts:
            if self.state in ("awaiting_human", "pending_execution"):
                self.finder.on_lift(sq, now)

        for sq in places:
            if self.state == "pending_execution":
                self._attempt_mirror_completion(sq)
                continue
            if self.state != "awaiting_human":
                continue
            move = self.finder.on_place(sq, now, self.board)
            if move:
                self._handle_candidate_move(move)

        if self.state == "awaiting_engine":
            self._consume_engine(now)

        if self.mode == "lichess" and now - self.last_lichess_poll >= self.cfg.lichess_poll_interval:
            self.last_lichess_poll = now
            self._poll_lichess(now)

        if self.mode == "hvh" and now - self.last_hvh_poll >= self.cfg.hvh_poll_interval:
            self.last_hvh_poll = now
            self._poll_hvh()

        if (self.state == "awaiting_human" and not self.mirror_tasks
                and now - self.last_resync >= self.cfg.resync_interval):
            self.last_resync = now
            self._resync()

        # Auto mode: follow whatever game is active on the server
        # (hvh first, then lichess, else engine play).
        if (self.cfg.mode == "auto" and self.mode != "lichess"
                and now - self.last_mode_check >= self.cfg.mode_check_interval):
            self.last_mode_check = now
            target = self._detect_mode()
            if target != self.mode:
                self.log.info("auto: switching %s -> %s", self.mode, target)
                self._enter_mode(target, adopt_server=(target == "hvh"))

        self._update_mismatch(now)
        if self.state == "game_over":
            self._check_auto_restart(now)
        self._render(now)

    # ------------------------------------------------------------------
    # Mirroring (opponent moves: red -> green prompt)
    # ------------------------------------------------------------------

    def _current_check_sq(self) -> Optional[str]:
        if self.board.is_check():
            king_sq = self.board.king(self.board.turn)
            if king_sq is not None:
                return chess.square_name(king_sq)
        return None

    def _mirror_move(self, uci: str, pre_board: Optional[chess.Board] = None) -> bool:
        """
        Stage an opponent move for physical execution by the player.

        Computes all physically-equivalent gestures (including castling:
        king directly, king dropped on the rook target, or a proper rook
        transfer), pushes the move onto the logical board and queues a
        prompt so the board blinks red -> green.

        Returns True if a prompt was queued; False if the move is already
        physically present on the board (nothing to prompt).
        """
        board_before = pre_board ifpre_board is not None else self.board
        try:
            move = chess.Move.from_uci(uci)
        except ValueError:
            self.log.warning("cannot mirror unparseable move %s", uci)
            return False
        if move not in board_before.legal_moves:
            self.log.warning("cannot mirror illegal move %s", uci)
            return False

        match_keys = {uci[:4]}
        from_squares = {uci[:2]}
        if board_before.is_castling(move):
            rook_from, rook_to = _castle_rook_transfer(board_before, move)
            match_keys.add(uci[:2] + rook_to)     # king dropped on rook target
            match_keys.add(rook_from + rook_to)   # proper rook transfer
            from_squares.add(rook_from)

        self.board = board_before
        self.board.push(move)
        self._note_fen()

        # If the pieces are already where they should be (e.g. the player
        # moved before the poll caught up), don't prompt.
        if self.reader.occupied_squares() == occupancy_of(self.board):
            self.log.info("move %s already executed on the board", uci)
            return False

        task = MirrorTask(
            uci=uci,
            to_square=uci[2:4],
            from_squares=from_squares,
            match_keys=match_keys,
            check_sq=self._current_check_sq(),
        )
        self.mirror_tasks.append(task)
        if self.state != "game_over":
            self.state = "pending_execution"
        return True

    def _attempt_mirror_completion(self, placed_sq: str) -> bool:
        """Check whether placing a lifted piece completes the head mirror task."""
        if not self.mirror_tasks:
            return False
        head = self.mirror_tasks[0]
        for from_sq in list(self.finder.lifted.keys()):
            if (from_sq + placed_sq) in head.match_keys:
                self.finder.lifted.pop(from_sq, None)
                self._complete_mirror()
                return True
        return False

    def _complete_mirror(self):
        if not self.mirror_tasks:
            return
        task = self.mirror_tasks.popleft()
        self.log.info("player executed move %s", task.uci)
        self.leds.clear()

        if self.mirror_tasks:
            return  # more prompts still queued

        self.state = "awaiting_human"
        if task.deferred_gameover is not None:
            winner, reason = task.deferred_gameover
            self.state = "game_over"
            self.log.info("game over (%s)", reason)
            self._flash_game_over(winner)
            return

        self._check_game_over()
        if self.state != "game_over":
            self._kick_engine_if_needed()

    def _kick_engine_if_needed(self) -> None:
        """
        In stockfish mode, if it is the engine's turn (we play Black, or the
        server is at the start position and we play Black), ask it to move.
        """
        if self.mode != "stockfish":
            return
        if self.state != "awaiting_human" or self.mirror_tasks:
            return
        if self._engine_inflight:
            return
        if self.board.turn != self.human_color:
            self._start_engine_move()

    # ------------------------------------------------------------------
    # Mismatch guidance
    # ------------------------------------------------------------------

    def _update_mismatch(self, now: float):
        if self.state in ("pending_execution", "game_over"):
            self._mismatch_since = None
            self._missing = set()
            self._extra = set()
            return

        expected = occupancy_of(self.board)
        physical = self.reader.occupied_squares()
        if expected == physical:
            if self._mismatch_since is not None:
                self.log.info("board is consistent again")
            self._mismatch_since = None
            self._missing = set()
            self._extra = set()
            return

        if self._mismatch_since is None:
            self._mismatch_since = now
        self._missing = expected - physical
        self._extra = physical - expected

    @property
    def guidance_visible(self) -> bool:
        return self._mismatch_since is not None and (
            time.time() - self._mismatch_since >= self.cfg.guidance_delay
        )

    # ------------------------------------------------------------------
    # Rendering
    # ------------------------------------------------------------------

    def _render(self, now: float):
        overlays: Dict[str, Tuple[int, int, int]] = {}

        # Local move confirmation has priority. This guarantees the white
        # from/to flash survives a very fast engine reply and is shown for
        # the full highlight_delay.
        if self._confirm_move and now < self._confirm_until:
            for sq in self._confirm_squares:
                overlays[sq] = WHITE
        elif self.mirror_tasks:
            # Unified red -> green prompt for ANY opponent move (engine,
            # lichess opponent, hvh inbound), any colour.
            head = self.mirror_tasks[0]
            blink_on = int(now * self.cfg.prompt_blink_hz * 2) % 2 == 0
            overlays[head.to_square] = GREEN if blink_on else DIM_GREEN
            for from_sq in sorted(head.from_squares):
                if from_sq != head.to_square:
                    overlays[from_sq] = RED if blink_on else DIM_RED
            if head.check_sq:
                overlays[head.check_sq] = ORANGE if blink_on else DIM_RED
        elif self.guidance_visible:
            for sq in self._missing:
                overlays[sq] = YELLOW
            for sq in self._extra:
                overlays[sq] = BLUE
        elif self._li_waiting:
            pulse = int(now * 1.5) % 2 == 0
            for sq in ("d4", "e4", "d5", "e5"):
                overlays[sq] = WHITE if pulse else (40, 40, 40)

        self.leds.render(overlays)

    def _flash_game_over(self, winner: Optional[bool]):
        if winner is None or self.mode == "hvh" or self.human_color is None:
            # Draw, or a fully local (hvh) game: neutral celebration.
            self.leds.flash_all(GOLD, times=3)
        elif winner == self.human_color:
            self.leds.flash_all(GREEN, times=3)
        else:
            self.leds.flash_all(RED, times=3)
        self.leds.clear()

    # ------------------------------------------------------------------
    # Game over / restart / resync
    # ------------------------------------------------------------------

    def _check_game_over(self) -> bool:
        if not self.board.is_game_over():
            return False
        winner = (not self.board.turn) if self.board.is_checkmate() else None
        self._declare_game_over(winner, self.board.result(claim_draw=True))
        return True

    def _declare_game_over(self, winner: Optional[bool], reason: str):
        if self.mirror_tasks:
            # Wait until the last prompted move has been physically executed.
            self.mirror_tasks[-1].deferred_gameover = (winner, reason)
            return
        self.log.info("game over (%s)", reason)
        self.state = "game_over"
        self._flash_game_over(winner)

    def _check_auto_restart(self, now: float):
        if not self.cfg.auto_restart:
            return
        if self.reader.occupied_squares() == INITIAL_OCCUPANCY:
            if self._reset_candidate_since is None:
                self._reset_candidate_since = now
            elif now - self._reset_candidate_since >= 2.0:
                self.log.info("board physically reset -- starting a new game")
                self._enter_mode(self._detect_mode())
        else:
            self._reset_candidate_since = None

    def _resync(self):
        if self.mode == "hvh":
            # HVH is fully handled by its own poller (with staleness and
            # undo guards); triggering it here keeps error paths (e.g.
            # rejected moves) from rolling back the local board.
            self._poll_hvh()
            return
        if self.mode != "stockfish":
            return
        fen = self.client.stockfish_fen()
        if not fen:
            return
        try:
            server_board = chess.Board(fen)
        except ValueError:
            self.log.warning("server returned invalid FEN: %s", fen)
            return
        if self.mirror_tasks:
            # Never clobber the board while a move is being mirrored/executed.
            return
        if server_board.fen() != self.board.fen():
            self.log.info("resyncing local board with server state")
            self.board = server_board
            self.finder.reset()
            self._mismatch_since = None
            self._check_game_over()
            self._kick_engine_if_needed()

    # ------------------------------------------------------------------
    # Candidate (local human) moves -- always confirmed with white flash
    # ------------------------------------------------------------------

    def _handle_candidate_move(self, uci: str):
        if self.state != "awaiting_human":
            self.log.debug("ignoring candidate %s in state %s", uci, self.state)
            return
        if self.mode == "stockfish":
            self._handle_stockfish_move(uci)
        elif self.mode == "hvh":
            self._handle_hvh_move(uci)
        elif self.mode == "lichess":
            self._handle_lichess_move(uci)

    def _confirm(self, uci: str, pre_board: Optional[chess.Board] = None):
        """White flash on the squares involved in a local player's move."""
        squares = [uci[:2], uci[2:4]]
        if pre_board is not None:
            try:
                move = chess.Move.from_uci(uci)
            except ValueError:
                move = None
            if move is not None and pre_board.is_castling(move):
                rook_from, rook_to = _castle_rook_transfer(pre_board, move)
                squares.extend([rook_from, rook_to])
        self._confirm_move = uci
        self._confirm_squares = squares
        self._confirm_until = time.time() + self.cfg.highlight_delay

    # -- stockfish -----------------------------------------------------

    def _handle_stockfish_move(self, uci: str):
        # Colour-aware: works identically for the human playing White or
        # Black vs the engine.
        if self.board.turn != self.human_color:
            self.log.debug("ignoring %s: not the human's turn", uci)
            return
        piece = self.board.piece_at(chess.parse_square(uci[:2]))
        if piece is None or piece.color != self.human_color:
            self.log.debug("ignoring %s: not the human's piece", uci)
            return

        pre = self.board.copy(stack=False)
        if not self.client.sf_make_human_move(uci):
            self.log.warning("server rejected human move %s; resyncing", uci)
            self.leds.flash_all(DIM_RED, times=2)
            self._resync()
            return

        self.board.push(chess.Move.from_uci(uci))
        self.log.info("human played %s", uci)
        self._confirm(uci, pre)

        if self._check_game_over():
            return

        self._start_engine_move()

    def _start_engine_move(self):
        self.state = "awaiting_engine"
        self._engine_result = None
        self._engine_started = time.time()
        self._engine_event.clear()
        self._engine_inflight = True
        gen = self._engine_generation

        def work():
            try:
                result = self.client.sf_play()
            except Exception as exc:
                self.log.warning("engine worker crashed: %s", exc)
                result = None
            # Discard results from threads left over from a previous mode.
            if gen == self._engine_generation:
                self._engine_result = result
                self._engine_event.set()

        threading.Thread(target=work, daemon=True, name="stockfish-move").start()

    def _consume_engine(self, now: float):
        if self._engine_event.is_set():
            ai_move = self._engine_result
            self._engine_event.clear()
            self._engine_inflight = False
            if not ai_move:
                self.log.warning("engine returned no move; resyncing")
                self.leds.flash_all(DIM_RED, times=2)
                self.state = "awaiting_human"
                self._resync()
                return
            self.log.info("engine plays %s", ai_move)
            queued = self._mirror_move(ai_move)
            if self._check_game_over():
                return
            if not queued:
                # Already physically present; nothing to prompt.
                self.state = "awaiting_human"
                self._kick_engine_if_needed()
        elif now - self._engine_started > self.cfg.engine_timeout + 5.0:
            self._engine_inflight = False
            self.log.warning("engine timed out; resyncing")
            self.leds.flash_all(DIM_RED, times=2)
            self.state = "awaiting_human"
            self._resync()

    # -- hvh -----------------------------------------------------------

    def _handle_hvh_move(self, uci: str):
        # Both players are human on this board; any legal move by either
        # side is accepted and confirmed with the white flash.
        if not self.client.hvh_make_move(uci):
            self.log.warning("server rejected hvh move %s; resyncing", uci)
            self.leds.flash_all(DIM_RED, times=2)
            self._resync()
            return

        pre = self.board.copy(stack=False)
        self.board.push(chess.Move.from_uci(uci))
        self.log.info("hvh move played: %s", uci)
        self._note_fen()
        self._confirm(uci, pre)
        self._check_game_over()

    def _find_single_transition(self, target: chess.Board) -> Optional[chess.Move]:
        """
        Find the unique legal move turning self.board into target.
        Returns None if zero or ambiguous matches exist.
        """
        hits: List[chess.Move] = []
        for move in self.board.legal_moves:
            probe = self.board.copy(stack=False)
            probe.push(move)
            if probe.fen() == target.fen():
                hits.append(move)
                if len(hits) > 1:
                    break
        if len(hits) == 1:
            return hits[0]
        return None

    def _poll_hvh(self):
        """
        Track the shared server HVH board.

        * If the server session goes idle while we are in hvh mode, leave
          (auto mode) or log it (forced hvh mode).
        * A server FEN equal to our own is synced.
        * A (changed) server FEN behind ours by 1..4 plies is a server-side
          undo -> rewind the local logical board (clears the yellow/blue).
        * A changed server FEN behind by more (>4) means the shared game was          reset; keep the local game.
        * A server FEN that never changes is a frozen snapshot from a
          server that doesn't refresh status["fen"] on make-move -- never
          roll back for it.
        * A server FEN ahead by legal forward moves is an inbound move
          from another board/client and is prompted red -> green.
        """
        snap = self._hvh_snapshot(force=True)
        if snap is None:
            return
        state = snap.get("state")

        if state != "playing":
            # Server session ended/reset while we are in hvh mode.
            if self._hvh_last_state == "playing":
                self.log.info("hvh: server session is no longer active (state=%r)", state)
            self._hvh_last_state = state
            if self.cfg.mode != "hvh" and self.state != "game_over":
                # auto mode: leave hvh and re-detect (stockfish/lichess)
                self._enter_mode(self._detect_mode())
            return

        self._hvh_last_state = "playing"

        if self.state == "game_over":
            return

        # Resolve a previously deferred divergent-position adoption.
        if self._hvh_pending_adoption is not None:
            if self.state == "awaiting_human" and not self.mirror_tasks:
                target = self._hvh_pending_adoption
                self._hvh_pending_adoption = None
                if target.fen() != self.board.fen():
                    self.log.info("hvh: adopting server position")
                    self.board = target
                    self.finder.reset()
                    self._note_fen()
                    self._check_game_over()
            return

        fen = snap.get("fen")
        if not fen:
            return
        try:
            target = chess.Board(fen)
        except ValueError:
            self.log.warning("hvh server returned invalid FEN: %s", fen)
            return

        server_fen = target.fen()
        fen_changed = server_fen != self._hvh_last_server_fen
        self._hvh_last_server_fen = server_fen

        if server_fen == self.board.fen():
            return

        # Server board is behind ours: either a server-side /hvh-undo
        # (the FEN *changed* since the last poll) or a stale frozen
        # snapshot from a server that never refreshes status["fen"].
        behind = self._plies_behind(target)
        if behind is not None:
            if not fen_changed:
                # Frozen snapshot (buggy server): never roll back.
                return
            if behind <= 4:
                self._rewind_hvh(target)
                return
            self.log.info("hvh: server board is far behind local; keeping local game")
            return

        # Server position is ahead: another board/client made a move.
        steps = 0
        while server_fen != self.board.fen() and steps < 6:
            move = self._find_single_transition(target)
            if move is None:
                self.log.warning("hvh: server position diverges; deferring adoption")
                self._hvh_pending_adoption = target
                return
            self._mirror_move(move.uci())
            self._check_game_over()
            steps += 1

    # -- lichess -------------------------------------------------------

    def _replay(self, moves: List[str]) -> Optional[chess.Board]:
        try:
            board = (chess.Board(self._li_initial_fen)
                     if self._li_initial_fen else chess.Board())
        except ValueError:
            board = chess.Board()
        for mv in moves:
            try:
                move = chess.Move.from_uci(mv)
            except ValueError:
                return None
            if move not in board.legal_moves:
                return None
            board.push(move)
        return board

    def _poll_lichess(self, now: float):
        status = self.client.lichess_status()
        if status is None:
            return
        state = status.get("state")

        if state in (None, "idle"):
            self._li_waiting = False
            self._li_stream_started = False
            if self.cfg.auto_seek and not self._li_seek_requested:
                self.log.info("lichess: seeking a game")
                self.client.li_search()
                self._li_seek_requested = True
            elif self.cfg.mode == "auto" and not self.cfg.auto_seek:
                self.log.info("lichess game ended/idle; leaving lichess mode")
                self._enter_mode("stockfish")
            return

        if state in ("searching", "found"):
            if not self._li_waiting:
                self.log.info("lichess: %s", state)
            self._li_waiting = True
            # The server only streams game state if /update-lichess-game has
            # been POSTed. Start it (and retry if it apparently died).
            if state == "found":
                if not self._li_stream_started:
                    if self.client.li_update_stream():
                        self._li_stream_started = True
                        self._li_stream_post_time = now
                elif now - self._li_stream_post_time > 6.0:
                    self.log.warning("lichess still 'found'; restarting updater")
                    self.client.li_update_stream()
                    self._li_stream_post_time = now
            return

        # state == "playing"
        self._li_waiting = False
        self._li_seek_requested = False

        # If we entered lichess while it was already playing, make sure an
        # update stream is running (rather than waiting for a "found" state).
        if not self._li_stream_started:
            if self.client.li_update_stream():
                self._li_stream_started = True
                self._li_stream_post_time = now

        gamedata = status.get("gamedata") or {}
        color = status.get("color")  # present only with the server patch
        if gamedata.get("type") == "gameFull":
            self._li_initial_fen = (gamedata.get("initialFen")
                                    or gamedata.get("initialFEN") or None)
            color = color or gamedata.get("color")
            if color in ("white", "black") and self.human_color is None:
                self.human_color = chess.WHITE if color == "white" else chess.BLACK
                self.log.info("lichess: we play %s", color)
            gamedata = gamedata.get("state") or {}
        elif color in ("white", "black") and self.human_color is None:
            self.human_color = chess.WHITE if color == "white" else chess.BLACK
            self.log.info("lichess: we play %s", color)

        moves_str = gamedata.get("moves") or ""
        moves = moves_str.split() if moves_str else []

        if moves != self._li_moves:
            self._li_last_change = now
            self._apply_lichess_moves(moves)

        # If the stream thread on the server died, state freezes at the last
        # gameState. Restart the updater if nothing changed for a long time.
        if (self._li_stream_started
                and now - self._li_last_change > self.cfg.lichess_stale_after):
            self.log.warning("lichess stream looks stale; restarting updater")
            self.client.li_update_stream()
            self._li_stream_post_time = now
            self._li_lastChange = now

        status_field = gamedata.get("status")
        if status_field and status_field not in ("started", "created"):
            winner = {"white": chess.WHITE, "black": chess.BLACK}.get(
                gamedata.get("winner"))
            self._declare_game_over(winner, f"lichess: {status_field}")

    def _apply_lichess_moves(self, moves: List[str]):
        # Incremental only after we already have a synced move list; the
        # first batch after entering lichess is treated as a full resync so
        # we don't replay/queue an entire mid-game move sequence as prompts.
        incremental = (
            self.lichess_ply_count > 0
            and len(moves) > self.lichess_ply_count
            and moves[: self.lichess_ply_count] == self._li_moves
        )
        if not incremental:
            self._li_full_resync(moves)
            return

        for mv in moves[self.lichess_ply_count:]:
            try:
                move = chess.Move.from_uci(mv)
            except ValueError:
                self.log.warning("lichess sent unparseable move %s; resyncing", mv)
                self._li_full_resync(moves)
                return
            if move not in self.board.legal_moves:
                self.log.warning("lichess move %s illegal locally; resyncing", mv)
                self._li_full_resync(moves)
                return

            # Our own move, already pushed locally when we sent it.
            if self.board.move_stack and self.board.peek() == move:
                continue

            mover = self.board.turn
            before_occ = occupancy_of(self.board)
            after_board = self.board.copy(stack=False)
            after_board.push(move)
            after_occ = occupancy_of(after_board)
            physical = self.reader.occupied_squares()

            if self.human_color is None:
                # Infer our colour from what physically happened:
                #   pieces still on origin squares        -> remote move
                #   pieces already on destination squares -> that was us
                if physical == before_occ and physical != after_occ:
                    self.human_color = not mover
                    self.log.info("lichess: inferred we play %s",
                                  "white" if self.human_color else "black")
                elif physical == after_occ:
                    self.human_color = mover
                    self.log.info("lichess: inferred we play %s",
                                  "white" if self.human_color else "black")

            if self.human_color is not None and mover != self.human_color:
                # Remote opponent move: prompt red -> green.
                self._mirror_move(mv)
            else:
                self.board.push(move)

        self.lichess_ply_count = len(moves)
        self._li_moves = list(moves)
        self._check_game_over()

    def _li_full_resync(self, moves: List[str]):
        new_board = self._replay(moves)
        if new_board is None:
            self.log.warning("cannot replay lichess move list; keeping local state")
            return

        self.log.info("lichess full resync (%d half-moves)", len(moves))
        self.finder.reset()
        self.mirror_tasks.clear()
        if self.state == "pending_execution":
            self.state = "awaiting_human"

        self.board = new_board

        if moves:
            before = self._replay(moves[:-1])
            if before is not None:
                mover = before.turn
                physical = self.reader.occupied_squares()
                before_occ = occupancy_of(before)
                after_occ = occupancy_of(new_board)

                if self.human_color is None:
                    if physical == before_occ and physical != after_occ:
                        self.human_color = not mover
                        self.log.info("lichess: inferred we play %s",
                                      "white" if self.human_color else "black")
                    elif physical == after_occ:
                        self.human_color = mover
                        self.log.info("lichess: inferred we play %s",
                                      "white" if self.human_color else "black")

                if (self.human_color is not None and mover != self.human_color
                        and physical == before_occ):
                    # The final remote move has not been executed yet:
                    # prompt it red -> green.
                    self.board = before
                    self._mirror_move(moves[-1])   # pushes final move again

        self.lichess_ply_count = len(moves)
        self._li_moves = list(moves)
        self._check_game_over()

    def _handle_lichess_move(self, uci: str):
        piece = self.board.piece_at(chess.parse_square(uci[:2]))
        if piece is None or piece.color != self.board.turn:
            self.log.debug("ignoring %s: not the side to move", uci)
            return

        if self.human_color is None:
            self.human_color = piece.color
            self.log.info("lichess: physical move tells us we play %s",
                          "white" if self.human_color else "black")
        elif piece.color != self.human_color:
            self.log.debug("ignoring %s: that's the opponent's piece", uci)
            return

        if not self.client.li_make_move(uci):
            self.log.warning("lichess rejected move %s", uci)
            self.leds.flash_all(DIM_RED, times=2)
            return

        pre = self.board.copy(stack=False)
        self.board.push(chess.Move.from_uci(uci))
        self._confirm(uci, pre)
        self.log.info("sent lichess move %s", uci)
        self._check_game_over()

# --------------------------------------------------------------------------
# Entry point
# --------------------------------------------------------------------------
def main(argv=None) -> int:
    cfg = DEFAULT_CONFIG

    log = setup_logging(cfg)
    log.info("chessboard main.py starting (mode=%s, simulate=%s)",
             cfg.mode, cfg.simulate)

    matrix = create_matrix(cfg, log)
    strip = create_leds(cfg, log)
    leds = LedView(strip, log)
    leds.clear()
    client = GameClient(cfg, log)

    while True:
        loop = GameLoop(cfg, matrix, leds, client, log)
        try:
            loop.run()
            break
        except Exception:
            log.error("fatal error, restarting loop in 5s:\n%s",
                      traceback.format_exc())
            time.sleep(5.0)

    return 0

if __name__ == "__main__":
    sys.exit(main())
